# Generated by Django 3.1.5 on 2021-01-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='concept',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='definition',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='card',
            name='topic',
        ),
    ]
