# Generated by Django 3.1.5 on 2021-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210121_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imgUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
