# Generated by Django 3.1.5 on 2021-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
